#!/bin/sh
,rbenvi() {
    command ,rbenvi "$@"
    [ -n "$SHELLNAME" ] && exec $SHELLNAME || echo "SHELLNAME not set."
}
# TODO:
# rehash-after() {
#   eval "function $1 { command $1 \"\$@\"; rehash }";
# }
# reexec-after() {
#   eval "function $1 { command $1 \"\$@\"; (see above) }"
# }
# Note: I don't think bash will work with the one-line style.
